return {
  id = "intro_nitori_seija",
  text = {
    nitori_001 = "동력 안정. 컨베이어 각도 정상. 화물 투입량도 목표치 안쪽.",
    nitori_002 = "좋아. 니토리식 자동 공장, 첫 시범운용 시작.",
    seija_001 = "흐응. 줄 맞춰 움직이는 물건들이라.",
    nitori_003 = "누구야? 관계자 외 출입 금지라고 적어놨을 텐데.",
    seija_002 = "봤어. 그래서 들어왔지. 금지라고 쓰면 확인하고 싶어지잖아.",
    nitori_004 = "확인 끝났으면 나가. 지금은 시험 중이야.",
    seija_003 = "시험이면 더더욱 있어야지. 제대로 망가지는지도 봐야 하니까.",
    nitori_005 = "망가뜨리는 건 시험 항목이 아니야.",
    seija_004 = "이상하네. 세상 물건은 보통 누가 만지면 망가지던데.",
    nitori_006 = "네가 일부러 이상하게 만지는 거겠지.",
    seija_005 = "처음 보는 사이인데 너무 정확히 말하네.",
    nitori_007 = "초면인 침입자가 컨베이어 앞에서 웃고 있으면 답은 하나야.",
    seija_006 = "그럼 하나만 살짝 뒤집어 볼까? 네 답이 맞는지 확인하게.",
    nitori_008 = "손 떼! 저 라인 멈추면 전체 계산 다시 해야 해.",
    seija_007 = "계산 다시 하는 얼굴, 꽤 볼만할 것 같은데.",
    nitori_009 = "너 이름 뭐야. 손해배상 청구서에 적어야 하니까.",
    seija_008 = "이름부터 묻는 거야? 보통은 차라도 내오지 않아?",
    nitori_010 = "차는 없어. 경고음은 있어.",
    seija_009 = "좋네. 공장도 시끄럽고 주인도 시끄럽고.",
    nitori_011 = "시범운용 항목 변경. 외부 방해 개체 대응 테스트.",
    seija_010 = "방해 개체라니. 너무 딱딱하잖아. 방문객이라고 불러.",
    nitori_012 = "방문객은 장비를 뒤집겠다고 예고하지 않아.",
    seija_011 = "그럼 예고를 안 하면 방문객이 되는 거네?",
    nitori_013 = "아니. 그럼 수상한 침입자에서 위험한 침입자로 승급이야.",
    seija_012 = "승급은 마음에 드는데, 잡히는 건 마음에 안 드네.",
    nitori_014 = "그럼 움직이지 마. 움직이면 바로 테스트 시작이야.",
  },
  bgm = { action = "play", path = "assets/audio/bgm1.mp3", volume = 0.4, loop = true },
  actors = {
    nitori = { name = "니토리", portrait = "nitori", pos = "left", emotion = "normal" },
    seija = { name = "세이자", portrait = "seija", pos = "right", emotion = "normal", flip = true },
  },
  lines = {
    { actor = "nitori", emotion = "normal", text = "nitori_001", bubble = "default" },
    { actor = "nitori", emotion = "smile", text = "nitori_002", bubble = "default", motion = "totter" },
    { actor = "seija", emotion = "doya", text = "seija_001", bubble = "default", motion = { type = "sway", power = 8, speed = 5 }, flip = true, sfx = "alert" },
    { actor = "nitori", emotion = "surprise", text = "nitori_003", bubble = "shout", motion = "shake" },
    { actor = "seija", emotion = "normal", text = "seija_002", bubble = "default", flip = true },
    { actor = "nitori", emotion = "angry", text = "nitori_004", bubble = "default", motion = "shake" },
    { actor = "seija", emotion = "question", text = "seija_003", bubble = "default", flip = true },
    { actor = "nitori", emotion = "normal", text = "nitori_005", bubble = "default" },
    { actor = "seija", emotion = "doya", text = "seija_004", bubble = "default", flip = true, motion = "sway" },
    { actor = "nitori", emotion = "angry", text = "nitori_006", bubble = "shout", motion = "shake" },
    { actor = "seija", emotion = "question", text = "seija_005", bubble = "default", flip = true },
    { actor = "nitori", emotion = "angry", text = "nitori_007", bubble = "default", sfx = "alert" },
    { bgm = { action = "fade", to = 0.25, duration = 0.8 }, wait = 0.2 },
    { actor = "seija", emotion = "doya", text = "seija_006", bubble = "default", flip = true, motion = "sway" },
    { actor = "nitori", emotion = "surprise", text = "nitori_008", bubble = "default" },
    { actor = "seija", emotion = "sigh", text = "seija_007", bubble = "default", flip = true },
    { actor = "nitori", emotion = "angry", text = "nitori_009", bubble = "default", motion = "shake" },
    { actor = "seija", emotion = "doya", text = "seija_008", bubble = "default", flip = true },
    { actor = "nitori", emotion = "smile", text = "nitori_010", bubble = "default" },
    { actor = "seija", emotion = "question", text = "seija_009", bubble = "default", flip = true },
    { actor = "nitori", emotion = "normal", text = "nitori_011", bubble = "default" },
    { actor = "seija", emotion = "doya", text = "seija_010", bubble = "default", flip = true, motion = "totter" },
    { actor = "nitori", emotion = "angry", text = "nitori_012", bubble = "default" },
    { actor = "seija", emotion = "sigh", text = "seija_011", bubble = "default", flip = true },
    { actor = "nitori", emotion = "smile", text = "nitori_013", bubble = "default" },
    { actor = "seija", emotion = "defeat", text = "seija_012", bubble = "default", flip = true },
    { actor = "nitori", emotion = "normal", text = "nitori_014", bubble = "default" },
  },
}
