return {
  id = "alice_workshop_transport",
  text = {
    alice_001 = "카와시로 니토리 씨, 맞지요? 잠깐 의뢰 상담을 해도 될까요.",
    nitori_001 = "운송 설비라면 들어볼게. 제작 대행이나 판매대 설치는 안 해.",
    alice_002 = "필요한 건 자동 운송이에요. 인형공방 안에서 부품과 완성품 이동이 자꾸 밀려서요.",
    nitori_002 = "인형 자체를 만드는 게 아니라, 실, 나무틀, 관절 부품, 완성 인형을 옮기는 라인?",
    alice_003 = "네. 작업대마다 필요한 물건이 다르고, 제가 직접 옮기면 집중이 끊겨요.",
    nitori_003 = "작업대 수, 재료 종류, 하루 이동량. 그 셋부터 필요해.",
    alice_004 = "작업대는 넷. 재료는 천, 실, 나무틀, 작은 금속 관절. 완성품은 보관함으로 보내면 돼요.",
    nitori_004 = "복잡하진 않네. 문제는 인형들이 움직이면서 라인을 건드리는지 여부야.",
    alice_005 = "그 아이들은 조심성이 있어요. 대부분은요.",
    nitori_005 = "대부분이라는 말이 제일 비싸지는 말인데.",
    marisa_001 = "오, 재미있는 얘기 중이네. 자동으로 인형이 배달되는 거냐?",
    alice_006 = "마리사. 지나가는 길이라기엔 너무 정확히 끼어드네요.",
    marisa_002 = "지나가다 들은 거야. 공방에서 뭔가 자동으로 움직이면 훔치기 편하잖아.",
    nitori_006 = "방금 훔친다고 했지?",
    marisa_003 = "참고했다고 해두자.",
    alice_007 = "그래서 잠금 장치도 필요할 것 같아요.",
    nitori_007 = "잠금은 운송 제어 범위에 들어가. 허가된 보관함만 받게 하면 돼.",
    marisa_004 = "쳇. 그럼 나는 나중에 다른 방법을 생각해야겠네.",
    alice_008 = "나중에 등장할 생각을 너무 숨기지 않는군요.",
    marisa_005 = "복선은 크게 깔아야 눈에 띄는 법이지. 그럼 나는 간다!",
    nitori_008 = "폭풍처럼 끼어들고 사라졌네.",
    alice_009 = "익숙해지면 덜 놀라요. 아마도요.",
    nitori_009 = "좋아. 마리사 대응까지 포함하면 라인은 더 단단하게 짜야겠어.",
    alice_010 = "가능할까요?",
    nitori_010 = "가능해. 단, 나는 운송만 맡아. 인형 제작, 품질 검사, 마법 제어는 네 담당.",
    alice_011 = "그 조건이면 충분해요. 저는 손을 비우고, 재료가 제때 도착하면 되니까요.",
    nitori_011 = "1단계는 재료 보급 라인. 2단계는 완성품 회수. 3단계는 외부 반출 차단.",
    alice_012 = "깔끔하네요. 계약서 가져왔어요.",
    nitori_012 = "준비성이 좋네. 이런 의뢰인은 마음에 들어.",
    alice_013 = "대신 공방 인형들이 낯선 장치를 보고 몰려들 수도 있어요.",
    nitori_013 = "그 말은 견적서에 위험 수당 한 줄 추가하라는 뜻이지?",
    alice_014 = "부정은 못 하겠네요.",
  },
  bgm = { action = "play", path = "assets/audio/bgm2.mp3", volume = 0.36, loop = true },
  actors = {
    nitori = { name = "니토리", portrait = "nitori", pos = "left", emotion = "normal" },
    alice = { name = "앨리스", portrait = "alice", pos = "right", emotion = "normal", flip = true },
    marisa = { name = "마리사", portrait = "marisa", pos = "center", emotion = "normal", visible = false },
  },
  lines = {
    { actor = "alice", emotion = "normal", text = "alice_001" },
    { actor = "nitori", emotion = "normal", text = "nitori_001" },
    { actor = "alice", emotion = "positive", text = "alice_002" },
    { actor = "nitori", emotion = "normal", text = "nitori_002" },
    { actor = "alice", emotion = "smile", text = "alice_003" },
    { actor = "nitori", emotion = "normal", text = "nitori_003" },
    { actor = "alice", emotion = "normal", text = "alice_004" },
    { actor = "nitori", emotion = "surprise", text = "nitori_004" },
    { actor = "alice", emotion = "confuse", text = "alice_005" },
    { actor = "nitori", emotion = "angry", text = "nitori_005" },
    { actor = "marisa", enter = { actor = "marisa", from = "right", duration = 0.32 }, emotion = "delight", text = "marisa_001", motion = "totter", sfx = "alert" },
    { actor = "alice", emotion = "surprise", text = "alice_006" },
    { actor = "marisa", emotion = "normal", text = "marisa_002" },
    { actor = "nitori", emotion = "surprise", text = "nitori_006", bubble = "shout" },
    { actor = "marisa", emotion = "confuse", text = "marisa_003" },
    { actor = "alice", emotion = "normal", text = "alice_007" },
    { actor = "nitori", emotion = "smile", text = "nitori_007" },
    { actor = "marisa", emotion = "angry", text = "marisa_004" },
    { actor = "alice", emotion = "disappointed", text = "alice_008" },
    { actor = "marisa", emotion = "delight", text = "marisa_005", motion = "sway" },
    { exit = { actor = "marisa", to = "left", duration = 0.28 }, wait = 0.28 },
    { actor = "nitori", emotion = "surprise", text = "nitori_008" },
    { actor = "alice", emotion = "confuse", text = "alice_009" },
    { actor = "nitori", emotion = "normal", text = "nitori_009" },
    { actor = "alice", emotion = "normal", text = "alice_010" },
    { actor = "nitori", emotion = "smile", text = "nitori_010" },
    { actor = "alice", emotion = "delight", text = "alice_011" },
    { actor = "nitori", emotion = "normal", text = "nitori_011" },
    { actor = "alice", emotion = "smile", text = "alice_012" },
    { actor = "nitori", emotion = "smile", text = "nitori_012" },
    { actor = "alice", emotion = "confuse", text = "alice_013" },
    { actor = "nitori", emotion = "angry", text = "nitori_013" },
    { actor = "alice", emotion = "smile", text = "alice_014" },
  },
}
