return {
  id = "moriya_omikuji_request",
  text = {
    sanae_001 = "저기, 카와시로 씨. 혹시 자동 운송 설비 상담도 받으시나요?",
    nitori_001 = "운송이라면 받지. 무엇을 어디에서 어디로 옮기고 싶은데?",
    sanae_002 = "모리야 신사의 오미쿠지입니다. 요즘 참배객이 늘어서 보충하러 뛰어다니고 있거든요.",
    nitori_002 = "오미쿠지를 만드는 건 신사 쪽 일이고, 나는 옮기는 라인만 봐.",
    sanae_003 = "맞아요! 역시 소문대로 이해가 빠르시네요.",
    nitori_003 = "소문?",
    sanae_004 = "요괴의 산에 공장을 세우고, 복잡한 운송도 척척 처리하는 캇파 기술자라고 들었어요.",
    nitori_004 = "그 소문은 마음에 드네. 견적은 마음에 안 들 수도 있지만.",
    sanae_005 = "신사 예산은 풍족하지 않지만, 신덕과 홍보 효과는 충분히 드릴 수 있어요.",
    nitori_005 = "홍보 효과는 화물로 못 세어. 현물은?",
    sanae_006 = "오이 절임, 신사 부적, 그리고 카나코 님의 공식 추천 문구 정도요.",
    nitori_006 = "추천 문구는 조금 쓸 만하네. 라인 조건부터 보자.",
    sanae_007 = "대길, 중길, 소길, 흉 상자가 각각 있고, 줄어든 쪽을 자동으로 뽑기대까지 보내고 싶어요.",
    nitori_007 = "그럼 재고 감지, 합류 라인, 우선순위 분기면 돼. 내용물 비율은 너희가 관리하고.",
    sanae_008 = "네. 운세 자체는 신사의 책임이고, 저는 보충 동선만 줄이고 싶어요.",
    nitori_008 = "좋아. 나는 상자에서 뽑기대까지 막히지 않게 흐름만 설계한다.",
    sanae_009 = "역시 부탁드리길 잘했네요!",
    nitori_009 = "아직 맡는다고 안 했어. 종이 걸림, 습기, 장난치는 텐구, 전부 고려해야 해.",
    sanae_010 = "텐구 장난까지요?",
    nitori_010 = "산에서 돌아가는 기계라면 기본 사양이지.",
    sanae_011 = "그럼 참배객이 몰려도 오미쿠지가 끊기지 않는 건가요?",
    nitori_011 = "보관함에 재고만 있으면. 빈 상자에서 운송할 수는 없어.",
    sanae_012 = "으음... 신덕 할부는 안 될까요?",
    nitori_012 = "신덕은 이자가 붙어도 계좌에 안 찍혀.",
    sanae_013 = "그럼 첫 달은 수동 보충 위치만 만들고, 다음 달에 자동 분기와 재고 감지를 추가할 수 있을까요?",
    nitori_013 = "현실적이네. 1단계는 단순 운송, 2단계는 재고 감지와 우선순위 분기.",
    sanae_014 = "좋아요. 모리야 신사 오미쿠지 자동 운송라인, 정식 의뢰합니다.",
    nitori_014 = "접수 완료. 대신 첫 시운전 때 대길 하나는 내가 뽑는다.",
    sanae_015 = "그건 새치기입니다.",
    nitori_015 = "기술자 우선 이용권이라고 부르면?",
    sanae_016 = "그래도 새치기입니다.",
    nitori_016 = "쳇. 신사는 쓸데없는 데 엄격하네.",
  },
  bgm = { action = "play", path = "assets/audio/bgm2.mp3", volume = 0.38, loop = true },
  actors = {
    nitori = { name = "니토리", portrait = "nitori", pos = "left", emotion = "normal" },
    sanae = { name = "사나에", portrait = "sanae", pos = "right", emotion = "normal", flip = true },
  },
  lines = {
    { actor = "sanae", emotion = "normal", text = "sanae_001" },
    { actor = "nitori", emotion = "normal", text = "nitori_001" },
    { actor = "sanae", emotion = "delight", text = "sanae_002", motion = "totter" },
    { actor = "nitori", emotion = "normal", text = "nitori_002" },
    { actor = "sanae", emotion = "kirat", text = "sanae_003" },
    { actor = "nitori", emotion = "surprise", text = "nitori_003" },
    { actor = "sanae", emotion = "doya", text = "sanae_004" },
    { actor = "nitori", emotion = "smile", text = "nitori_004" },
    { actor = "sanae", emotion = "emb", text = "sanae_005" },
    { actor = "nitori", emotion = "normal", text = "nitori_005" },
    { actor = "sanae", emotion = "normal", text = "sanae_006" },
    { actor = "nitori", emotion = "smile", text = "nitori_006" },
    { actor = "sanae", emotion = "normal", text = "sanae_007" },
    { actor = "nitori", emotion = "normal", text = "nitori_007" },
    { actor = "sanae", emotion = "confuse", text = "sanae_008" },
    { actor = "nitori", emotion = "normal", text = "nitori_008" },
    { actor = "sanae", emotion = "delight", text = "sanae_009", motion = "totter" },
    { actor = "nitori", emotion = "angry", text = "nitori_009" },
    { actor = "sanae", emotion = "surprise", text = "sanae_010" },
    { actor = "nitori", emotion = "normal", text = "nitori_010" },
    { actor = "sanae", emotion = "kirat", text = "sanae_011" },
    { actor = "nitori", emotion = "smile", text = "nitori_011" },
    { actor = "sanae", emotion = "confuse", text = "sanae_012" },
    { actor = "nitori", emotion = "normal", text = "nitori_012" },
    { actor = "sanae", emotion = "normal", text = "sanae_013" },
    { actor = "nitori", emotion = "smile", text = "nitori_013" },
    { actor = "sanae", emotion = "delight", text = "sanae_014" },
    { actor = "nitori", emotion = "smile", text = "nitori_014" },
    { actor = "sanae", emotion = "angry", text = "sanae_015", bubble = "shout" },
    { actor = "nitori", emotion = "surprise", text = "nitori_015" },
    { actor = "sanae", emotion = "normal", text = "sanae_016" },
    { actor = "nitori", emotion = "defeat", text = "nitori_016" },
  },
}
